###ID
@id = {{createPiloto.response.body.data.id}}

### lista completa
GET http://localhost:3000/api/pilotos

### Encontrar uno

GET http://localhost:3000/api/pilotos/{{id}}

### mandar nuevo piloto
# @name createPiloto
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Max Verstappen",
    "team": 1,
    "nro": 1,
    "nationality": "Pais bajeano/Neerlandés",
    "role": "Primer piloto"
}

### editar piloto con el id
PUT http://localhost:3000/api/pilotos/{{id}}
Content-Type: application/json

{
    "name": "Max Verstappen",
    "team": 2,
    "nro": 1,
    "nationality": "Neerlandés",
    "role": "Primer piloto"
}

### editar parcialmente piloto, por ahora igual que put
PATCH http://localhost:3000/api/pilotos/{{id}}
Content-Type: application/json

{
    "nationality": "Neerlandés"
}

###borrar un piloto
DELETE http://localhost:3000/api/pilotos/{{id}}