###ID
@id = {{createPiloto.response.body.data.id}}

### GET ALL
GET http://localhost:3000/api/pilotos/

### GET ONE

GET http://localhost:3000/api/pilotos/{{id}}

### POST Ferrari (escuderia 1)
# @name createPiloto
POST http://localhost:3000/api/pilotos/
Content-Type: application/json

{
    "name": "Charles Leclerc",
    "escuderia": 2,
    "num": 16,
    "nationality": "Monegasque",
    "role": "Primer piloto"
}

### POST Ferrari (escuderia 1) - Compañero
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Lewis Hamilton",
    "escuderia": 2,
    "num": 44,
    "nationality": "British",
    "role": "Segundo piloto"
}

### POST Alpine (escuderia 2)
# @name createPiloto
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Franco Colapinto",
    "escuderia": 2,
    "num": 43,
    "nationality": "Argentinian",
    "role": "Segundo piloto"
}

### POST Alpine (escuderia 2) - Compañero
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Pierre Gasly",
    "escuderia": 2,
    "num": 10,
    "nationality": "French",
    "role": "Primer piloto"
}

### POST Racing Bulls (escuderia 3) - Pilotos
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Isack Hadjar",
    "escuderia": 1,
    "num": 6,
    "nationality": "French",
    "role": "Primer piloto"
}

### POST Racing Bulls (escuderia 3) - Pilotos
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Liam Lawson",
    "escuderia": 1,
    "num": 30,
    "nationality": "New Zealander",
    "role": "Segundo piloto"
}

### POST Osama Bin Russell
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "George Russell",
    "escuderia": 3,
    "num": 63,
    "nationality": "Inglés",
    "role": "Primer piloto"
}

### POST Talibantonelli
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Andrea Kimi Antonelli",
    "escuderia": 3,
    "num": 12,
    "nationality": "Italiano",
    "role": "Segundo piloto"
}

### PUT
PUT http://localhost:3000/api/pilotos/{{id}}
Content-Type: application/json

{
    "name": "Max Verstappen",
    "escuderia": 2,
    "num": 1,
    "nationality": "Neerlandés",
    "role": "Primer piloto"
}

### PATCH
PATCH http://localhost:3000/api/pilotos/5
Content-Type: application/json

{
      "racing_series": 1
}

### DELETE
DELETE http://localhost:3000/api/pilotos/{{id}}