###ID
@id = {{createEscuderia.response.body.data.id}}

### GET ALL

GET http://localhost:3000/api/escuderias

### GET ONE
GET http://localhost:3000/api/escuderias/{{id}}

### POST 1
# @name createEscuderia
POST http://localhost:3000/api/escuderias
Content-Type: application/json

{
    "name": "Scuderia Ferrari",
    "fundation": 1929,
    "nationality": "Italia",
    "engine": "Ferrari 066/10",
    "marca": 1,
    "pilotos": [5, 4]
}

### POST 2
# @name createEscuderia
POST http://localhost:3000/api/escuderias
Content-Type: application/json

{
    "name": "Mercedes-AMG Petronas F1 Team",
    "fundation": 2010,
    "nationality": "Alemania",
    "engine": "Mercedes M15 E Performance",
    "marca": 2
}

### PUT (UPDATE COMPLETO)
PUT http://localhost:3000/api/escuderias/1
Content-Type: application/json

{
    "name": "Racing Bulls Formula One Team",
    "fundation": 2024,
    "nationality": "Italia",
    "engine": "Honda RBPT",
    "marcaId": 8,
    "pilotos": [3,4]
}

### PATCH (UPDATE PARCIAL)
PATCH http://localhost:3000/api/escuderias/2
Content-Type: application/json

{
    "categoria": 1
}

###DELETE
DELETE http://localhost:3000/api/escuderias/12

