###ID
@id = {{createEscuderia.response.body.data.id}}

### GET ALL
GET http://localhost:3000/api/escuderias

### GET ONE
GET http://localhost:3000/api/escuderias/{{id}}

### POST 1
# @name createEscuderia
POST http://localhost:3000/api/escuderias
Content-Type: application/json

{
    "name": "Scuderia Ferrari",
    "fundation_year": 1929,
    "nationality": "Italy",
    "engine": "Ferrari 066/10",
    "categoria": 1
}

### POST 2
# @name createEscuderia
POST http://localhost:3000/api/escuderias
Content-Type: application/json

{
    "name": "Alpine F1 Team",
    "fundation": 2021,
    "nationality": "France",
    "engine": "Renault E-Tech RE23",
    "pilotos": [5,6]
}

### PUT (UPDATE COMPLETO)
PUT http://localhost:3000/api/escuderias/1
Content-Type: application/json

{
    "name": "Racing Bulls Formula One Team",
    "fundation": 2024,
    "nationality": "Italy",
    "engine": "Honda RBPT",
    "pilotos": [3,4]
}

### PATCH (UPDATE PARCIAL)
PATCH http://localhost:3000/api/escuderias/{{id}}
Content-Type: application/json

{
    "engine": "Ferrari HP"
}

###DELETE
DELETE http://localhost:3000/api/escuderias/{{id}}

