

@id = {{createUsuario.response.body.data.id}}

### lista de Usuarios
GET http://localhost:3000/api/usuarios


### GET ONE usuario
GET http://localhost:3000/api/usuarios/{{id}}


### Crear nuevo usuario
# @name createUsuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "username": "juanperez1",
    "name": "Juan",
    "surname": "Perez",
    "email": "juan.perez@example.com",
    "password": "securepassword123",
    "date_of_birth": "1990-05-15",
    "bio":" Apasionado por los motores"

}


### Actualizar usuario
PATCH http://localhost:3000/api/usuarios/{{id}}
Content-Type: application/json

{
    "bio": "Amante de los autos y la velocidad"
}

### Eliminar usuario
DELETE http://localhost:3000/api/usuarios/{{id}}

