### Listado de carreras de la temporada 2023
GET https://api.openf1.org/v1/meetings?year=2026

### GET CARRERA
GET https://api.openf1.org/v1/meetings?year=2026&country_code=SGP

### get sesiones de carrera
GET https://api.openf1.org/v1/sessions?meeting_key=1296

### lISTADO cIRCUITO
GET https://api.multiviewer.app/api/v1/circuits/61/2026