@id = {{createBlogpost.response.body.id}}


### lista de Blogposts
GET http://localhost:3000/api/blogposts

### GET ONE blogpost
GET http://localhost:3000/api/blogposts/{{id}}

### Crear nuevo blogpost
# @name createBlogpost
POST http://localhost:3000/api/blogposts
Content-Type: application/json

{
    "title": "Los mejores autos deportivos de 2024",
    "content": "En este artículo, exploramos los autos deportivos más emocionantes que llegarán al mercado en 2024...",
    "authorId": 4
}


### Actualizar blogpost
PATCH http://localhost:3000/api/blogposts/{{id}}
Content-Type: application/json

{
    "content": "En este artículo actualizado, exploramos los autos deportivos más emocionantes que llegarán al mercado en 2024...",
}


### Eliminar blogpost
DELETE http://localhost:3000/api/blogposts/{{id}}
