/**
 * Lista de nacionalidades con código IOC en mayúsculas y nombre en español.
 * Usada para dropdowns en el frontend y para validar el campo nationality de las entidades.
 * Los códigos coinciden con los archivos SVG en uploads/flags/{code}.svg
 */
export const nationalities = [
  { code: 'AFG', name: 'Afganistán' },
  { code: 'ALB', name: 'Albania' },
  { code: 'GER', name: 'Alemania' },
  { code: 'AND', name: 'Andorra' },
  { code: 'ANG', name: 'Angola' },
  { code: 'ANT', name: 'Antigua y Barbuda' },
  { code: 'KSA', name: 'Arabia Saudita' },
  { code: 'ALG', name: 'Argelia' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'ARM', name: 'Armenia' },
  { code: 'AUS', name: 'Australia' },
  { code: 'AUT', name: 'Austria' },
  { code: 'AZE', name: 'Azerbaiyán' },
  { code: 'BAH', name: 'Bahamas' },
  { code: 'BRN', name: 'Baréin' },
  { code: 'BAN', name: 'Bangladés' },
  { code: 'BAR', name: 'Barbados' },
  { code: 'BLR', name: 'Bielorrusia' },
  { code: 'BEL', name: 'Bélgica' },
  { code: 'BIZ', name: 'Belice' },
  { code: 'BEN', name: 'Benín' },
  { code: 'BHU', name: 'Bután' },
  { code: 'BOL', name: 'Bolivia' },
  { code: 'BIH', name: 'Bosnia y Herzegovina' },
  { code: 'BOT', name: 'Botsuana' },
  { code: 'BRA', name: 'Brasil' },
  { code: 'BRU', name: 'Brunéi' },
  { code: 'BUL', name: 'Bulgaria' },
  { code: 'BUR', name: 'Burkina Faso' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'CPV', name: 'Cabo Verde' },
  { code: 'CAM', name: 'Camboya' },
  { code: 'CMR', name: 'Camerún' },
  { code: 'CAN', name: 'Canadá' },
  { code: 'QAT', name: 'Catar' },
  { code: 'CHA', name: 'Chad' },
  { code: 'CHI', name: 'Chile' },
  { code: 'CHN', name: 'China' },
  { code: 'CYP', name: 'Chipre' },
  { code: 'COL', name: 'Colombia' },
  { code: 'COM', name: 'Comoras' },
  { code: 'CGO', name: 'Congo' },
  { code: 'COD', name: 'Congo (Rep. Dem.)' },
  { code: 'PRK', name: 'Corea del Norte' },
  { code: 'KOR', name: 'Corea del Sur' },
  { code: 'CRC', name: 'Costa Rica' },
  { code: 'CIV', name: 'Costa de Marfil' },
  { code: 'CRO', name: 'Croacia' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'DEN', name: 'Dinamarca' },
  { code: 'DMA', name: 'Dominica' },
  { code: 'ECU', name: 'Ecuador' },
  { code: 'EGY', name: 'Egipto' },
  { code: 'ESA', name: 'El Salvador' },
  { code: 'UAE', name: 'Emiratos Árabes Unidos' },
  { code: 'ERI', name: 'Eritrea' },
  { code: 'SVK', name: 'Eslovaquia' },
  { code: 'SLO', name: 'Eslovenia' },
  { code: 'ESP', name: 'España' },
  { code: 'USA', name: 'Estados Unidos' },
  { code: 'EST', name: 'Estonia' },
  { code: 'SWZ', name: 'Esuatini' },
  { code: 'ETH', name: 'Etiopía' },
  { code: 'PHI', name: 'Filipinas' },
  { code: 'FIN', name: 'Finlandia' },
  { code: 'FIJ', name: 'Fiyi' },
  { code: 'FRA', name: 'Francia' },
  { code: 'GAB', name: 'Gabón' },
  { code: 'GAM', name: 'Gambia' },
  { code: 'GEO', name: 'Georgia' },
  { code: 'GHA', name: 'Ghana' },
  { code: 'GRN', name: 'Granada' },
  { code: 'GRE', name: 'Grecia' },
  { code: 'GUA', name: 'Guatemala' },
  { code: 'GUI', name: 'Guinea' },
  { code: 'GEQ', name: 'Guinea Ecuatorial' },
  { code: 'GBS', name: 'Guinea-Bisáu' },
  { code: 'GUY', name: 'Guyana' },
  { code: 'HAI', name: 'Haití' },
  { code: 'HON', name: 'Honduras' },
  { code: 'HUN', name: 'Hungría' },
  { code: 'IND', name: 'India' },
  { code: 'INA', name: 'Indonesia' },
  { code: 'IRQ', name: 'Irak' },
  { code: 'IRI', name: 'Irán' },
  { code: 'IRL', name: 'Irlanda' },
  { code: 'ISL', name: 'Islandia' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Italia' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'JPN', name: 'Japón' },
  { code: 'JOR', name: 'Jordania' },
  { code: 'KAZ', name: 'Kazajistán' },
  { code: 'KEN', name: 'Kenia' },
  { code: 'KGZ', name: 'Kirguistán' },
  { code: 'KIR', name: 'Kiribati' },
  { code: 'KUW', name: 'Kuwait' },
  { code: 'LAO', name: 'Laos' },
  { code: 'LES', name: 'Lesoto' },
  { code: 'LAT', name: 'Letonia' },
  { code: 'LBN', name: 'Líbano' },
  { code: 'LBR', name: 'Liberia' },
  { code: 'LBA', name: 'Libia' },
  { code: 'LIE', name: 'Liechtenstein' },
  { code: 'LTU', name: 'Lituania' },
  { code: 'LUX', name: 'Luxemburgo' },
  { code: 'MKD', name: 'Macedonia del Norte' },
  { code: 'MAD', name: 'Madagascar' },
  { code: 'MAS', name: 'Malasia' },
  { code: 'MAW', name: 'Malaui' },
  { code: 'MDV', name: 'Maldivas' },
  { code: 'MLI', name: 'Malí' },
  { code: 'MLT', name: 'Malta' },
  { code: 'MAR', name: 'Marruecos' },
  { code: 'MRI', name: 'Mauricio' },
  { code: 'MTN', name: 'Mauritania' },
  { code: 'MEX', name: 'México' },
  { code: 'FSM', name: 'Micronesia' },
  { code: 'MDA', name: 'Moldavia' },
  { code: 'MON', name: 'Mónaco' },
  { code: 'MGL', name: 'Mongolia' },
  { code: 'MNE', name: 'Montenegro' },
  { code: 'MOZ', name: 'Mozambique' },
  { code: 'MYA', name: 'Myanmar' },
  { code: 'NAM', name: 'Namibia' },
  { code: 'NRU', name: 'Nauru' },
  { code: 'NEP', name: 'Nepal' },
  { code: 'NCA', name: 'Nicaragua' },
  { code: 'NIG', name: 'Níger' },
  { code: 'NGR', name: 'Nigeria' },
  { code: 'NOR', name: 'Noruega' },
  { code: 'NZL', name: 'Nueva Zelanda' },
  { code: 'OMA', name: 'Omán' },
  { code: 'NED', name: 'Países Bajos' },
  { code: 'PAK', name: 'Pakistán' },
  { code: 'PLW', name: 'Palaos' },
  { code: 'PLE', name: 'Palestina' },
  { code: 'PAN', name: 'Panamá' },
  { code: 'PNG', name: 'Papúa Nueva Guinea' },
  { code: 'PAR', name: 'Paraguay' },
  { code: 'PER', name: 'Perú' },
  { code: 'POL', name: 'Polonia' },
  { code: 'POR', name: 'Portugal' },
  { code: 'GBR', name: 'Reino Unido' },
  { code: 'CAF', name: 'República Centroafricana' },
  { code: 'CZE', name: 'República Checa' },
  { code: 'DOM', name: 'República Dominicana' },
  { code: 'RWA', name: 'Ruanda' },
  { code: 'ROU', name: 'Rumania' },
  { code: 'RUS', name: 'Rusia' },
  { code: 'SAM', name: 'Samoa' },
  { code: 'SKN', name: 'San Cristóbal y Nieves' },
  { code: 'SMR', name: 'San Marino' },
  { code: 'VIN', name: 'San Vicente y las Granadinas' },
  { code: 'LCA', name: 'Santa Lucía' },
  { code: 'STP', name: 'Santo Tomé y Príncipe' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'SRB', name: 'Serbia' },
  { code: 'SEY', name: 'Seychelles' },
  { code: 'SLE', name: 'Sierra Leona' },
  { code: 'SGP', name: 'Singapur' },
  { code: 'SYR', name: 'Siria' },
  { code: 'SOM', name: 'Somalia' },
  { code: 'SRI', name: 'Sri Lanka' },
  { code: 'RSA', name: 'Sudáfrica' },
  { code: 'SUD', name: 'Sudán' },
  { code: 'SSD', name: 'Sudán del Sur' },
  { code: 'SWE', name: 'Suecia' },
  { code: 'SUI', name: 'Suiza' },
  { code: 'SUR', name: 'Surinam' },
  { code: 'THA', name: 'Tailandia' },
  { code: 'TPE', name: 'Taiwán' },
  { code: 'TAN', name: 'Tanzania' },
  { code: 'TJK', name: 'Tayikistán' },
  { code: 'TLS', name: 'Timor Oriental' },
  { code: 'TOG', name: 'Togo' },
  { code: 'TGA', name: 'Tonga' },
  { code: 'TTO', name: 'Trinidad y Tobago' },
  { code: 'TUN', name: 'Túnez' },
  { code: 'TKM', name: 'Turkmenistán' },
  { code: 'TUR', name: 'Turquía' },
  { code: 'TUV', name: 'Tuvalu' },
  { code: 'UKR', name: 'Ucrania' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'URU', name: 'Uruguay' },
  { code: 'UZB', name: 'Uzbekistán' },
  { code: 'VAN', name: 'Vanuatu' },
  { code: 'VAT', name: 'Vaticano' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'VIE', name: 'Vietnam' },
  { code: 'YEM', name: 'Yemen' },
  { code: 'DJI', name: 'Yibuti' },
  { code: 'ZAM', name: 'Zambia' },
  { code: 'ZIM', name: 'Zimbabue' },
] as const;

export type NationalityCode = (typeof nationalities)[number]['code'];
