### ID

@id = {{createSesion.response.body.data.id}}

### GET ALL - Obtener todas las sesiones

GET http://localhost:3000/api/sesion

### GET ONE - Obtener una sesión específica por ID

GET http://localhost:3000/api/sesion/{{id}}

### POST - Crear una nueva sesión

# @name createSesion
### ===== GRAN PREMIO DE AZERBAIYÁN (ID: 12) =====

### POST - FP1 Azerbaiyán
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 Azerbaiyán",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-09-19T10:00:00Z",
  "fecha_Hora_fin": "2025-09-19T11:00:00Z",
  "carrera": 12,
  "resultados": [1, 2, 3]
}

### POST - FP2 Azerbaiyán
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP2 Azerbaiyán",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-09-19T14:00:00Z",
  "fecha_Hora_fin": "2025-09-19T15:00:00Z",
  "carrera": 12,
  "resultados": [1, 2, 3]
}

### POST - FP3 Azerbaiyán
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP3 Azerbaiyán",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-09-20T11:00:00Z",
  "fecha_Hora_fin": "2025-09-20T12:00:00Z",
  "carrera": 12,
  "resultados": [1, 2, 3]
}

### POST - Qualifying Azerbaiyán
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Qualifying Azerbaiyán",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-09-20T14:00:00Z",
  "fecha_Hora_fin": "2025-09-20T15:00:00Z",
  "carrera": 12,
  "resultados": [1, 2, 3]
}

### POST - Race Azerbaiyán
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Race Azerbaiyán",
  "tipo_Sesion": "GP",
  "fecha_Hora_inicio": "2025-09-21T13:00:00Z",
  "fecha_Hora_fin": "2025-09-21T15:00:00Z",
  "carrera": 12,
  "resultados": [1, 2, 3]
}

### ===== GRAN PREMIO DE SINGAPUR (ID: 13) =====

### POST - FP1 Singapur
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 Singapur",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-03T10:30:00Z",
  "fecha_Hora_fin": "2025-10-03T11:30:00Z",
  "carrera": 13,
  "resultados": [1, 2, 3]
}

### POST - FP2 Singapur
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP2 Singapur",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-03T14:00:00Z",
  "fecha_Hora_fin": "2025-10-03T15:00:00Z",
  "carrera": 13,
  "resultados": [1, 2, 3]
}

### POST - FP3 Singapur
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP3 Singapur",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-04T11:30:00Z",
  "fecha_Hora_fin": "2025-10-04T12:30:00Z",
  "carrera": 13,
  "resultados": [1, 2, 3]
}

### POST - Qualifying Singapur
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Qualifying Singapur",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-10-04T14:00:00Z",
  "fecha_Hora_fin": "2025-10-04T15:00:00Z",
  "carrera": 13,
  "resultados": [1, 2, 3]
}

### POST - Race Singapur
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Race Singapur",
  "tipo_Sesion": "GP",
  "fecha_Hora_inicio": "2025-10-05T13:00:00Z",
  "fecha_Hora_fin": "2025-10-05T15:00:00Z",
  "carrera": 13,
  "resultados": [1, 2, 3]
}
### ===== GRAN PREMIO DE ESTADOS UNIDOS (ID: 6) =====


### POST - FP1 Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 Estados Unidos",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-17T15:00:00Z",
  "fecha_Hora_fin": "2025-10-17T15:00:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### POST - FP2 Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP2 Estados Unidos",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-17T19:00:00Z",
  "fecha_Hora_fin": "2025-10-17T19:00:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### POST - FP3 Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP3 Estados Unidos",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-18T16:00:00Z",
  "fecha_Hora_fin": "2025-10-18T16:00:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### POST - Sprint Shootout Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Sprint Shootout Estados Unidos",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-10-18T19:30:00Z",
  "fecha_Hora_fin": "2025-10-18T19:30:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### POST - Sprint Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Sprint Estados Unidos",
  "tipo_Sesion": "Sprint",
  "fecha_Hora_inicio": "2025-10-19T18:00:00Z",
  "fecha_Hora_fin": "2025-10-19T18:00:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### POST - Qualifying Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Qualifying Estados Unidos",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-10-19T20:00:00Z",
  "fecha_Hora_fin": "2025-10-19T20:00:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### POST - Race Estados Unidos
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Race Estados Unidos",
  "tipo_Sesion": "GP",
  "fecha_Hora_inicio": "2025-10-19T21:00:00Z",
  "fecha_Hora_fin": "2025-10-19T21:00:00Z",
  "carrera": 6,
  "resultados": [1, 2, 3]
}

### ===== GRAN PREMIO DE MÉXICO (ID: 7) =====

### POST - FP1 México
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 México",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-24T17:00:00Z",
  "fecha_Hora_fin": "2025-10-24T17:00:00Z",
  "carrera": 7,
  "resultados": [1, 2, 3]
}

### POST - FP2 México
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP2 México",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-24T21:00:00Z",
  "fecha_Hora_fin": "2025-10-24T21:00:00Z",
  "carrera": 7,
  "resultados": [1, 2, 3]
}

### POST - FP3 México
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP3 México",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-10-25T18:00:00Z",
  "fecha_Hora_fin": "2025-10-25T18:00:00Z",
  "carrera": 7,
  "resultados": [1, 2, 3]
}

### POST - Qualifying México
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Qualifying México",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-10-25T21:00:00Z",
  "fecha_Hora_fin": "2025-10-25T21:00:00Z",
  "carrera": 7,
  "resultados": [1, 2, 3]
}

### POST - Race México
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Race México",
  "tipo_Sesion": "GP",
  "fecha_Hora_inicio": "2025-10-26T20:00:00Z",
  "fecha_Hora_fin": "2025-10-26T20:00:00Z",
  "carrera": 7,
  "resultados": [1, 2, 3]
}

### ===== GRAN PREMIO DE BRASIL (ID: 8) =====

### POST - FP1 Brasil
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 Brasil",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-11-07T15:00:00Z",
  "fecha_Hora_fin": "2025-11-07T15:00:00Z",
  "carrera": 8,
  "resultados": [1, 2, 3]
}

### POST - Sprint Shootout Brasil
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Sprint Shootout Brasil",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-11-07T19:00:00Z",
  "fecha_Hora_fin": "2025-11-07T19:00:00Z",
  "carrera": 8,
  "resultados": [1, 2, 3]
}

### POST - Sprint Brasil
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Sprint Brasil",
  "tipo_Sesion": "Sprint",
  "fecha_Hora_inicio": "2025-11-08T14:00:00Z",
  "fecha_Hora_fin": "2025-11-08T14:00:00Z",
  "carrera": 8,
  "resultados": [1, 2, 3]
}

### POST - Qualifying Brasil
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Qualifying Brasil",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-11-08T18:00:00Z",
  "fecha_Hora_fin": "2025-11-08T18:00:00Z",
  "carrera": 8,
  "resultados": [1, 2, 3]
}

### POST - Race Brasil
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Race Brasil",
  "tipo_Sesion": "GP",
  "fecha_Hora_inicio": "2025-11-09T18:00:00Z",
  "fecha_Hora_fin": "2025-11-09T18:00:00Z",
  "carrera": 8,
  "resultados": [1, 2, 3]
}

### ===== GRAN PREMIO DE LAS VEGAS (ID: 9) =====

### POST - FP1 Las Vegas
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 Las Vegas",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-11-20T02:30:00Z",
  "fecha_Hora_fin": "2025-11-20T02:30:00Z",
  "carrera": 9,
  "resultados": [1, 2, 3]
}

### POST - FP2 Las Vegas
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP2 Las Vegas",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-11-20T06:00:00Z",
  "fecha_Hora_fin": "2025-11-20T06:00:00Z",
  "carrera": 9,
  "resultados": [1, 2, 3]
}

### POST - FP3 Las Vegas
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP3 Las Vegas",
  "tipo_Sesion": "FP",
  "fecha_Hora_inicio": "2025-11-21T02:30:00Z",
  "fecha_Hora_fin": "2025-11-21T02:30:00Z",
  "carrera": 9,
  "resultados": [1, 2, 3]
}

### POST - Qualifying Las Vegas
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Qualifying Las Vegas",
  "tipo_Sesion": "Q",
  "fecha_Hora_inicio": "2025-11-21T06:00:00Z",
  "fecha_Hora_fin": "2025-11-21T06:00:00Z",
  "carrera": 9,
  "resultados": [1, 2, 3]
}

### POST - Race Las Vegas
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Race Las Vegas",
  "tipo_Sesion": "GP",
  "fecha_Hora_inicio": "2025-11-22T06:00:00Z",
  "fecha_Hora_fin": "2025-11-22T06:00:00Z",
  "carrera": 9,
  "resultados": [1, 2, 3]
}

### PUT - Actualizar una sesión completa

PUT http://localhost:3000/api/sesion/{{id}}
Content-Type: application/json
{
  "name": "Qualifying Updated",
  "fecha_Hora_inicio": "2023-10-01T15:00:00Z",
  "fecha_Hora_fin": "2023-10-01T15:00:00Z",
  "fecha_Hora_fin": "2023-10-01T16:00:00Z",
  "carrera": 1,
  "resultados": [4, 5]
}

### PATCH - Actualizar parcialmente una sesión

PATCH http://localhost:3000/api/sesion/{{id}}
Content-Type: application/json

{
  "name": "Qualifying Updated",
  "fecha_Hora_inicio": "2023-10-01T15:00:00Z"

"fecha_Hora_fin": "2023-10-01T15:00:00Z",}

### DELETE - Eliminar una sesión

DELETE http://localhost:3000/api/sesion/{{id}}



### post - Crear sesión carrera 
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "Carrera de Australia",
  "tipo_Sesion":"Race",   
  "fecha_Hora_inicio": "2024-03-17T14:00:00Z",
  "fecha_Hora_fin": "2024-03-17T14:00:00Z",
  "fecha_Hora_fin": "2024-03-17T16:00:00Z",
  "carrera": 1,
  "resultados": [4, 5]
}


### post - Crear sesión practica
POST http://localhost:3000/api/sesion
Content-Type: application/json

{
  "name": "FP1 Australia",
  "tipo_Sesion":"Practice",   
  "fecha_Hora_inicio": "2024-03-15T11:00:00Z",
  "fecha_Hora_fin": "2024-03-15T11:00:00Z",
  "fecha_Hora_fin": "2024-03-15T12:00:00Z",
  "carrera": 1,
  "resultados": [4, 5]
}