###ID
@id = {{createCategoria.response.body.data.id}}

### GET ALL
GET http://localhost:3000/api/categorias

###GET ONE
GET http://localhost:3000/api/categorias/4

### POST F1
# @name createCategoria
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "name": "Fórmula 1"
}

###PUT F2 -> F3 
PUT http://localhost:3000/api/categorias/2
Content-Type: application/json

{
    "name": "F2"
}

###PATCH
PATCH http://localhost:3000/api/categorias/1
Content-Type: application/json

{
    "pilotos": 1
}

###DELETE
DELETE http://localhost:3000/api/categorias/4