### lista completa
GET http://localhost:3000/api/pilotos

### mandar nuevo piloto
POST http://localhost:3000/api/pilotos
Content-Type: application/json

{
    "name": "Max Verstappen",
    "team": "Red Bull",
    "nro": 1,
    "nationality": "Pais bajeano/Neerlandés",
    "role": "Primer piloto",
}

### editar piloto con el id provisto, chequear que el id que nos da en GET sea el mismo del link de abajo
PUT http://localhost:3000/api/pilotos/
Content-Type: application/json

{
    "name": "Max Verstappen",
    "team": "Red Bull",
    "nro": 1,
    "nationality": "Neerlandés",
    "role": "Primer piloto"
}

### editar parcialmente piloto con id provisto, , chequear que el id que nos da en GET sea el mismo del link de abajo
PATCH http://localhost:3000/api/pilotos/
Content-Type: application/json

{
    "nationality": "Neerlandés"
}

###borrar un piloto
DELETE http://localhost:3000/api/pilotos/